services:
  cortex_on:
    build:
      context: ./cortex_on
      dockerfile: Dockerfile
    volumes:
      - ./cortex_on:/app
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: always

  agentic_browser:
    build:
      context: ./ta-browser
      dockerfile: Dockerfile
    volumes:
      - ./ta-browser:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - cortex_on
      - agentic_browser
    restart: always
