version: '3.8'

services:
  cortex_on:
    build:
      context: ./cortex_on
      dockerfile: Dockerfile
    volumes:
      - ./cortex_on:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: always
    network_mode: host
    privileged: true
    depends_on:
      - multi_language_env

  agentic_browser:
    build:
      context: ./ta-browser
      dockerfile: Dockerfile
    volumes:
      - ./ta-browser:/app
    env_file:
      - .env
    restart: always
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - cortex_on
      - agentic_browser
    restart: always
    network_mode: host

  # Multi-language environment container
  multi_language_env:
    container_name: cortexon_multi_env
    build:
      context: ./cortex_on/multi_lang_env
      dockerfile: Dockerfile
    volumes:
      - multi_language_code:/app
      - ./cortex_on/multi_lang_env/setup:/setup
    working_dir: /app
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: tail -f /dev/null

volumes:
  multi_language_code:
